### ISSUE TITLE
More idiomatic npm package name

### ISSUE THREAD

**Issue by sholladay** [anthony-nardi/2d-quadtree-js#1]
Remove the "js" for a more friendly name. See the tips section of npm's [package.json](https://docs.npmjs.com/files/package.json) documentation.

Something like this ...

``` sh
export THING='2d-quadtree-js';
export NEW_THING='2d-quadtree';
npm deprecate "$THING"@"<=1.0.3" "This package has been renamed to $NEW_THING. Install using $NEW_THING instead.";

```

Then edit the `name` in `package.json`, and finally ...

``` sh
npm publish
```

**Comment by anthony-nardi** [comment]
Thanks dude.  I finally got around to doing this... but I definitely appreciate your feedback, so awesome.  Should I wait for you to verify if I actually fixed it before I close the issue?  I tested it myself, installing the old package (got the response that it is deprecated) and then successfully installing the newly named package.

**Comment by sholladay** [comment]
No problem! I just verified that this is fixed. Looks good. :)
